### PR TITLE
Allow for a single-file import of all elements stylesheets

### PR DESCRIPTION
**Pull request by lennym**
Move the import of the govuk-elements styles into a single, standalone file so they can be imported as a single import statement without also including govuk_frontent_toolkit files.

#### What problem does the pull request solve?

We use a sass compiler which is npm-aware (https://npmjs.com/npm-sass), and so generally don't use configured `includePaths` when compiling. However, the main sass file in this repo is only compilable if the `includePaths` are set.

By moving the govuk-elements-sass code (as distinct from the govuk_frontend_toolkit code), we can `@import "govuk-elements-sass"` in our stylesheets and have them compile correctly (note the `sass` property added to package.json supports this shorthand, as opposed to having to specify a full file path)

This will also support any users who wish to import the elements code alone, without also importing govuk_frontend_toolkit for whatever reason.

#### What type of change is it?

- Bug fix (non-breaking change which fixes an issue)

#### Has the documentation been updated?

- I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by gemmaleigh** [comment]
Thanks @lennym!

The relationship between the govuk-elements-sass files and the govuk_frontend_toolkit isn't explicit (ideally the imports would be at the top of each file - not that it would resolve the issue with includePaths - but at least the relationship between the two would be clearer.)

I've been trying to avoid making breaking changes - which is why they're still listed at the top.

This looks good, I'm hoping to release a new version of govuk-elements-sass shortly and will include this in that release.

**Comment by lennym** [comment]
Thanks a lot @gemmaleigh.
One thing I might suggest,

**Comment by gemmaleigh** [comment]
I won't be able to merge this PR as-is, as the package is build from assets in `assets/`, which is where the files will need splitting. Are you happy to do this?

**Comment by lennym** [comment]
I think I see what you mean... the same set of changes should be made to the files in the `assets` directory in the repo root?

Will do. Give me 5 minutes.

**Comment by gemmaleigh** [comment]
You'll only need to make the changes once in the assets directory, there's a `gulp package` task which I'll run before publishing the package, that'll copy everything to /packages/.

https://github.com/alphagov/govuk_elements/blob/master/gulpfile.js#L127

**Comment by lennym** [comment]
I've pushed the changes in assets - actually an extra change to also group the govuk-frontend-toolkit files as well, as IMO this makes it a lot clearer what is coming from where.

If you want me to undo the changes in `packages` then I'll `rebase -i` them out.

**Comment by gemmaleigh** [comment]
If you could undo the changes in packages (aside from the change to the package.json file) and ensure those two new files are copied over, that would be great - thanks!

**Comment by lennym** [comment]
Done. Let me know if I need to do anything else.

**Pull request merged**
