### PR TITLE
Adds source code link for Rural Payments website

### PR DESCRIPTION
**Pull request by pflannery**
Makes it easier to find the source code behind the style guide example.

### CODE REVIEW

**Comment by pflannery** [comment]
Not sure where the Land Registry website source code is so haven't added it in this PR

**Comment by gemmaleigh** [comment]
Thanks @pflannery! 
I'll ask Mat Johnson (@demotive) if he can update the Land Registry guide as a separate PR.

**Comment by pflannery** [comment]
thanks @gemmaleigh

**Comment by Demotive** [comment]
@gemmaleigh - The Land Registry style guide fell by the wayside for a long time, and isn't being maintained (long story). A new one is in the works (another long story). I'm making a note to add a PR to this repo when we're up and running.

**Pull request merged**
