### PR TITLE
[Discuss:] GOV.UK Verify style radios and checkboxes

### PR DESCRIPTION
**Pull request by gemmaleigh**
Larger hit area radio buttons and checkboxes.

Screenshot before:

before - example radio buttons and checkboxes form elements gov uk elements

Screenshot after:

example radio buttons and checkboxes form elements gov uk elements

Pros:
- a larger hit area for the control
- the selected radio or checkbox is more obvious (background, border and bold text)
- This fixes issue: #166 (jump in Safari when radio button is selected)

Cons:
- This requires extra markup within each block label `<span><span class="inner"></span></span>`

### CODE REVIEW

**Comment by edwardhorsford** [comment]
I'm *strongly* in favour of bigger radio and checkboxes. They're much better.

I'm not sure we still need the selection state / boxes with these changes. Though they are good on mobile.

Other thoughts:
* The checkboxes and radios are not vertically centred
* We should avoid bolding up the selected text. This can cause jarring movement, particularly if it causes text to wrap to two lines.

**Comment by edwardhorsford** [comment]
NB - if we want to be hacky we could use `-webkit-text-stroke-width: 0.5px;` or similar which will give a bit of a bold appearance, but not change the width of the text.

**Comment by edwardhorsford** [comment]
Any examples of hover styles? For reference, I coincidentally made this last week:
http://address-lookup-prototype.herokuapp.com/option-2/delivery-address (search for anything).

**Comment by tombye** [comment]
The description doesn't seem to explain the pros of using this design for radio buttons/checkboxes (over just making the native control bigger).

I'd be interested to know the reasons for the change to the windows 8/10/mobile style.

**Comment by aduggin** [comment]
We'll need to check these for accessibility - need to make sure they work in assistive technologies as expected.
Gemma - could you add test cases to the sandbox?
I've added example for the current style for testing:
https://govuk-accessibility-sandbox.herokuapp.com/patterns/checkboxes-group/
https://govuk-accessibility-sandbox.herokuapp.com/patterns/radio-buttons/

**Comment by edwardhorsford** [comment]
I've seen some services with a fair amount of text within the radios, including bold for headings. Would probably be good if we avoid changing the weight on selection for this reason too.

**Comment by tombye** [comment]
This may be possible without the extra markup (using some CSS3 features), if it we were ok with a certain level of coverage for the CSS (above version 8 for IE and possibly some other older clients).

I've done a test for what I mean, be interested in some reckons on it (needs proper testing):

https://github.com/tombye/custom-field-controls

**Comment by timpaul** [comment]
Thrilled to see this discussion happening ;-)

I second Ed's comment about the grey backgrounds - research has suggested they don't really get people to click the labels, so they're really just reducing contrast. Mobile might be a different case.

Can we design an A/B test to see if what effect these changes have?

**Comment by joelanman** [comment]
I'm in favour of big, clear controls for all browsers. Even when browsers do support making built-in controls bigger, theyre still often not as clear as they could be, or fit the GOV.UK style.

In research so far, I don't think the borders or grey boxes add much in terms of usability, and they detract in terms of contrast, and extra visual noise. So we don't have them on Verify, however, we haven't done loads of research on mobile.

**Comment by gemmaleigh** [comment]
I'm closing this for now, as it's not in a mergable state and it was raised for discussion only. 
I'm away until the 15th of April. I'll reopen once I'm back and we can look at a better solution then.

**Pull request closed without merging**
