### PR TITLE
[For discussion] Examples of phase tags

### PR DESCRIPTION
**Pull request by gemmaleigh**
#### What problem does the pull request solve?

This example was missing from GOV.UK elements, add an example to show
how phase tags can be used outside of the phase banner.

#### Screenshots (if appropriate):

alpha and beta banners gov uk elements

#### What type of change is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Put an `x` in all the boxes that apply

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by edwardhorsford** [comment]
I think it would be good to have a sentence about when and how we would expect these to be used.

I think it may be clearer if there's only one screenshot, and only one html snippet. To me it's clear which bit of text you need to change.

**Comment by gemmaleigh** [comment]
image

**Comment by robinwhittleton** [comment]
Looks good, but it’ll need some text as to why you’d use this outside of a phase banner. Maybe something like:

> Phase tags are mostly used inside phase banners as an indication of the state of a project. It’s possible to use them outside phase banners, for example as part of a service header.

With appropriate links to Tim’s headers work.

**Comment by robinwhittleton** [comment]
Will merge this next week unless I hear any dissent.

**Pull request merged**
