### PR TITLE
[Do not merge, for discussion]. Don't style html elements without a class or parent class

### PR DESCRIPTION
**Pull request by gemmaleigh**
Closing this PR, as it is split into three new PRs.

1. Require the use of a class to apply any govuk elements styles
https://github.com/alphagov/govuk_elements/pull/134

2. Use a common base class and modifier class pattern for lists, panels and icons.
https://github.com/alphagov/govuk_elements/pull/135

### CODE REVIEW

**Comment by edwardhorsford** [comment]
Out of interest, what's the thinking behind not styling element selectors - particularly where they're unlikely to change?

Alternately, would an approach be to have the styles under `.details`, but then style the element with ```details {
   @extend .details;
}```

**Comment by timpaul** [comment]
I like the idea of using classes for styling elements, but then making it
easy for people to extend elements with those styles. Then people can
choose how they want to work.

What about an extra Sass file that does all the extending of the basic
typographic elements, but that's commented out by default? User's could
then choose to activate it and to define a class that it's scoped to.

**Comment by gemmaleigh** [comment]
Hi @timpaul, that sounds good. I was thinking that would sit in the prototype kit.

**Comment by timpaul** [comment]
Yep - sounds like a plan

**Pull request closed without merging**
