### PR TITLE
Generate a lockfile for Yarn and update Travis to use Yarn

### PR DESCRIPTION
**Pull request by gemmaleigh**
Add  a yarn lockfile for Travis.

Add `yarn check --integrity` to keep 'package.json' and 'yarn.lock' in
sync.

### CODE REVIEW

**Comment by robinwhittleton** [comment]
I ran the first new command locally from the branch and got:

```$ yarn check --integrity
yarn check v0.21.3
error Lockfile does not contain pattern: "govuk_frontend_toolkit@^5.1.2"
error Couldn't find an integrity hash file
error Found 2 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.```

Are we expecting Travis to have run `yarn install` first?

**Comment by gemmaleigh** [comment]
This PR has been open for a few days! I think the Lockfile needs updating. I'll do that.

**Comment by nickcolley** [comment]
Nice 👍  Should we update the docs recommending yarn over the npm client? (If we do)

**Comment by robinwhittleton** [comment]
OK, the rebase is working for me, will merge. @nickcolley potentially, but that’s a separate issue. At this point yarn is still an option rather than a recommendation.

**Pull request merged**
